/**
 * ManageSpace Orgs API
 * ManageSpace Orgs API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Condition } from './condition';
import { Position } from './position';
import { UnitFeature } from './unitFeature';

export class BaseCreateUnit {
    /**
    * Unit Name
    */
    'unitName': string;
    /**
    * Unit Description
    */
    'unitDescription': string | null;
    /**
    * Unit Type ID
    */
    'unitTypeId': number;
    /**
    * Status
    */
    'statusId': number;
    /**
    * Length
    */
    'length': number;
    /**
    * Width
    */
    'width': number;
    /**
    * Height
    */
    'height': number | null;
    /**
    * Size
    */
    'size': number | null;
    /**
    * Metric
    */
    'metricId': number;
    /**
    * Standard Price
    */
    'standardPrice': number | null;
    /**
    * Tax
    */
    'tax': number | null;
    /**
    * Security Deposit
    */
    'unitSecurityDeposit': number | null;
    /**
    * Walk through order
    */
    'walkThroughOrder': number | null;
    /**
    * Currency
    */
    'currencyId': number | null;
    /**
    * Floor
    */
    'floor': number | null;
    /**
    * Notes
    */
    'notes': string | null;
    'position': Position;
    /**
    * Unit Features
    */
    'unitFeatures': Array<UnitFeature>;
    /**
    * Unit Conditions
    */
    'conditions': Array<Condition>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "unitName",
            "baseName": "unitName",
            "type": "string"
        },
        {
            "name": "unitDescription",
            "baseName": "unitDescription",
            "type": "string"
        },
        {
            "name": "unitTypeId",
            "baseName": "unitTypeId",
            "type": "number"
        },
        {
            "name": "statusId",
            "baseName": "statusId",
            "type": "number"
        },
        {
            "name": "length",
            "baseName": "length",
            "type": "number"
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "number"
        },
        {
            "name": "height",
            "baseName": "height",
            "type": "number"
        },
        {
            "name": "size",
            "baseName": "size",
            "type": "number"
        },
        {
            "name": "metricId",
            "baseName": "metricId",
            "type": "number"
        },
        {
            "name": "standardPrice",
            "baseName": "standardPrice",
            "type": "number"
        },
        {
            "name": "tax",
            "baseName": "tax",
            "type": "number"
        },
        {
            "name": "unitSecurityDeposit",
            "baseName": "unitSecurityDeposit",
            "type": "number"
        },
        {
            "name": "walkThroughOrder",
            "baseName": "walkThroughOrder",
            "type": "number"
        },
        {
            "name": "currencyId",
            "baseName": "currencyId",
            "type": "number"
        },
        {
            "name": "floor",
            "baseName": "floor",
            "type": "number"
        },
        {
            "name": "notes",
            "baseName": "notes",
            "type": "string"
        },
        {
            "name": "position",
            "baseName": "position",
            "type": "Position"
        },
        {
            "name": "unitFeatures",
            "baseName": "unitFeatures",
            "type": "Array<UnitFeature>"
        },
        {
            "name": "conditions",
            "baseName": "conditions",
            "type": "Array<Condition>"
        }    ];

    static getAttributeTypeMap() {
        return BaseCreateUnit.attributeTypeMap;
    }
}

