/**
 * ManageSpace Orgs API
 * ManageSpace Orgs API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SettingResponseValue } from './settingResponseValue';

export class CreateSettingRequest {
    'value': SettingResponseValue;
    /**
    * Standard setting type ID.
    */
    'standardSettingTypeId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "value",
            "baseName": "value",
            "type": "SettingResponseValue"
        },
        {
            "name": "standardSettingTypeId",
            "baseName": "standardSettingTypeId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CreateSettingRequest.attributeTypeMap;
    }
}

