/**
 * ManageSpace Orgs API
 * ManageSpace Orgs API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BaseCreateUnit } from './baseCreateUnit';

export class CreateUnitsRequest {
    /**
    * Units
    */
    'units': Array<BaseCreateUnit>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "units",
            "baseName": "units",
            "type": "Array<BaseCreateUnit>"
        }    ];

    static getAttributeTypeMap() {
        return CreateUnitsRequest.attributeTypeMap;
    }
}

