/**
 * ManageSpace Orgs API
 * ManageSpace Orgs API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SiteAmenity } from './siteAmenity';
import { UnitFeature } from './unitFeature';

export class CreateOrgRequest {
    /**
    * Organization name
    */
    'orgName': string;
    /**
    * Organization description
    */
    'orgDescription': string;
    /**
    * A list of default amenity ids
    */
    'defaultAmenities'?: Array<SiteAmenity>;
    /**
    * A list of default unit feature ids
    */
    'defaultFeatures'?: Array<UnitFeature>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "orgName",
            "baseName": "orgName",
            "type": "string"
        },
        {
            "name": "orgDescription",
            "baseName": "orgDescription",
            "type": "string"
        },
        {
            "name": "defaultAmenities",
            "baseName": "defaultAmenities",
            "type": "Array<SiteAmenity>"
        },
        {
            "name": "defaultFeatures",
            "baseName": "defaultFeatures",
            "type": "Array<UnitFeature>"
        }    ];

    static getAttributeTypeMap() {
        return CreateOrgRequest.attributeTypeMap;
    }
}

