/**
 * ManageSpace Orgs API
 * ManageSpace Orgs API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Position } from './position';
import { StandardMapFeatureTypeDto } from './standardMapFeatureTypeDto';

export class MapFeatureResponseDto {
    /**
    * Map Feature ID
    */
    'mapFeatureId': string;
    /**
    * Org ID
    */
    'orgId': string;
    /**
    * Site ID
    */
    'siteId': string;
    /**
    * Location ID
    */
    'locationId': string;
    'standardMapFeatureType': StandardMapFeatureTypeDto;
    'position': Position;
    /**
    * Width of the map feature
    */
    'width': number;
    /**
    * Height of the map feature
    */
    'height': number;
    /**
    * Depth of the map feature
    */
    'depth': number;
    /**
    * Floor of the map feature
    */
    'floor'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "mapFeatureId",
            "baseName": "mapFeatureId",
            "type": "string"
        },
        {
            "name": "orgId",
            "baseName": "orgId",
            "type": "string"
        },
        {
            "name": "siteId",
            "baseName": "siteId",
            "type": "string"
        },
        {
            "name": "locationId",
            "baseName": "locationId",
            "type": "string"
        },
        {
            "name": "standardMapFeatureType",
            "baseName": "standardMapFeatureType",
            "type": "StandardMapFeatureTypeDto"
        },
        {
            "name": "position",
            "baseName": "position",
            "type": "Position"
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "number"
        },
        {
            "name": "height",
            "baseName": "height",
            "type": "number"
        },
        {
            "name": "depth",
            "baseName": "depth",
            "type": "number"
        },
        {
            "name": "floor",
            "baseName": "floor",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return MapFeatureResponseDto.attributeTypeMap;
    }
}

