/**
 * ManageSpace Orgs API
 * ManageSpace Orgs API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class OrgResponse {
    /**
    * Organization ID
    */
    'orgId': string;
    /**
    * Organization name
    */
    'orgName': string;
    /**
    * Organization description
    */
    'orgDescription': string;
    /**
    * Time of creation
    */
    'createdAt': Date;
    /**
    * userId of who created the merchandise
    */
    'createdBy': string;
    /**
    * Time of the last update
    */
    'updatedAt': Date;
    /**
    * userId of who updated the merchandise
    */
    'updatedBy': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "orgId",
            "baseName": "orgId",
            "type": "string"
        },
        {
            "name": "orgName",
            "baseName": "orgName",
            "type": "string"
        },
        {
            "name": "orgDescription",
            "baseName": "orgDescription",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "createdBy",
            "baseName": "createdBy",
            "type": "string"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date"
        },
        {
            "name": "updatedBy",
            "baseName": "updatedBy",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return OrgResponse.attributeTypeMap;
    }
}

