/**
 * ManageSpace Orgs API
 * ManageSpace Orgs API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class OrgSettingResponse {
    /**
    * Organization ID.
    */
    'orgId': string;
    /**
    * Number of days before a tenant can move out when requesting.
    */
    'daysBeforeMoveOut': number;
    /**
    * Number of minutes between rescheduling a new notification.
    */
    'notificationDelayMinutes': number;
    /**
    * Max number for reminders attempt.
    */
    'maxReminderAttempts': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "orgId",
            "baseName": "orgId",
            "type": "string"
        },
        {
            "name": "daysBeforeMoveOut",
            "baseName": "daysBeforeMoveOut",
            "type": "number"
        },
        {
            "name": "notificationDelayMinutes",
            "baseName": "notificationDelayMinutes",
            "type": "number"
        },
        {
            "name": "maxReminderAttempts",
            "baseName": "maxReminderAttempts",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return OrgSettingResponse.attributeTypeMap;
    }
}

