/**
 * ManageSpace Orgs API
 * ManageSpace Orgs API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class SiteAmenity {
    /**
    * Site Amenity Id
    */
    'amenityId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amenityId",
            "baseName": "amenityId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SiteAmenity.attributeTypeMap;
    }
}

