/**
 * ManageSpace Orgs API
 * ManageSpace Orgs API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class StandardMapFeatureTypeDto {
    /**
    * Standard Map Feature Type ID
    */
    'standardMapFeatureTypeId': string;
    /**
    * Code Name
    */
    'codeName': string;
    /**
    * Display Name
    */
    'displayName': string;
    /**
    * Description
    */
    'description'?: string;
    /**
    * Resource Name
    */
    'resourceName': string;
    /**
    * Hex Color
    */
    'hexColor': string;
    /**
    * Opacity
    */
    'opacity'?: number;
    /**
    * Width
    */
    'width': number;
    /**
    * Height
    */
    'height': number;
    /**
    * Depth
    */
    'depth': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "standardMapFeatureTypeId",
            "baseName": "standardMapFeatureTypeId",
            "type": "string"
        },
        {
            "name": "codeName",
            "baseName": "codeName",
            "type": "string"
        },
        {
            "name": "displayName",
            "baseName": "displayName",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "resourceName",
            "baseName": "resourceName",
            "type": "string"
        },
        {
            "name": "hexColor",
            "baseName": "hexColor",
            "type": "string"
        },
        {
            "name": "opacity",
            "baseName": "opacity",
            "type": "number"
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "number"
        },
        {
            "name": "height",
            "baseName": "height",
            "type": "number"
        },
        {
            "name": "depth",
            "baseName": "depth",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return StandardMapFeatureTypeDto.attributeTypeMap;
    }
}

