/**
 * ManageSpace Orgs API
 * ManageSpace Orgs API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class UpdateOrgSettingRequest {
    /**
    * Number of days before a tenant can move out when requesting.
    */
    'daysBeforeMoveOut': number;
    /**
    * Number of minuets a user can request a reminder for.
    */
    'notificationDelayMinutes'?: number;
    /**
    * Number of times a user can request a reminder for the same notification.
    */
    'maxReminderAttempts'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "daysBeforeMoveOut",
            "baseName": "daysBeforeMoveOut",
            "type": "number"
        },
        {
            "name": "notificationDelayMinutes",
            "baseName": "notificationDelayMinutes",
            "type": "number"
        },
        {
            "name": "maxReminderAttempts",
            "baseName": "maxReminderAttempts",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return UpdateOrgSettingRequest.attributeTypeMap;
    }
}

